source/accounts/urls.py
from django.urls import path
from accounts.views import login_view, logout_view, register_view, UsersView,\
    user_activate, UserDetailView, UserPersonalInfoChangeView, UserPasswordChangeView

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('register/activate/', user_activate, name='user_activate'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('<int:pk>/update', UserPersonalInfoChangeView.as_view(), name='update'),
    path('<int:pk>/password_change', UserPasswordChangeView.as_view(), name='password_change'),
    path('users/', UsersView.as_view(), name='all_users_view')
]

app_name = 'accounts'

source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/v2/', include('api_v2.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from webapp.views import *

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('tracker/<int:pk>/', TrackerView.as_view(), name='tracker'),
    path('tracker/add/', TrackerCreateView.as_view(), name='tracker_add'),
    path('tracker/<int:pk>/edit/', TrackerUpdate.as_view(), name='update_tracker'),
    path('tracker/<int:pk>/delete/', DeleteTracker.as_view(), name='delete_tracker'),
    path('tracker/type/', TypeView.as_view(), name='type_views'),
    path('tracker/type/add/', TypeAddView.as_view(), name='add_type'),
    path('tracker/type/delete/<int:pk>/', DeleteType.as_view(), name='delete_type'),
    path('tracker/type/update/<int:pk>/', UpdateTypeView.as_view(), name='update_type'),
    path('tracker/status/', StatusView.as_view(), name='status_views'),
    path('tracker/status/add/', StatusAddView.as_view(), name='add_status'),
    path('tracker/status/update/<int:pk>/', UpdateStatusView.as_view(), name='update_status'),
    path('tracker/status/delete/<int:pk>/', DeleteStatus.as_view(), name='delete_status'),
    path('projects/', ProjectView.as_view(), name='projects'),
    path('project/<int:pk>/', ProjectDetailView.as_view(), name='project_detail'),
    path('project/add/', ProjectCreateView.as_view(), name='project_create'),
    path('project/<int:pk>/edit/', ProjectUpdate.as_view(), name='project_update'),
    path('project/<int:pk>/delete/', ProjectDelete.as_view(), name='delete_project'),
    path('project/<int:pk>/add-tracker/', TrackerForProjectCreateView.as_view(), name='create_new_tracker')
]

app_name = 'webapp'

source/accounts/models.py
from uuid import uuid4
from django.db import models
from django.contrib.auth.models import User
from webapp.models import Project


class Profile(models.Model):
    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE, verbose_name='Пользователь')
    birth_date = models.DateField(null=True, blank=True, verbose_name='birth date')
    text = models.TextField(null=True, blank=True, verbose_name='about', max_length=2000)
    avatar = models.ImageField(null=True, blank=True, upload_to='user_pics', verbose_name='Аватар')
    site = models.URLField(max_length=255, null=True, blank=True, verbose_name='site')

    def __str__(self):
        return self.user.get_full_name() + "'s Profile"

    class Meta:
        verbose_name = 'Профиль'

        verbose_name_plural = 'Профили'


class Token(models.Model):
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE,
                             verbose_name='user', related_name='registration_tokens')
    token = models.UUIDField(verbose_name='Token', default=uuid4)

    def __str__(self):
        return str(self.token)

source/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from accounts.models import Profile


class UserCreationForm(forms.Form):
    username = forms.CharField(max_length=100, label='Username', required=True)
    password = forms.CharField(max_length=100, label='Password', required=True,
                               widget=forms.PasswordInput)
    password_confirm = forms.CharField(max_length=100, label='Password Confirm', required=True,
                                       widget=forms.PasswordInput)
    email = forms.EmailField(label='Email', required=True)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        try:
            User.objects.get(email=email)
            raise ValidationError('User with this email already exists',
                                  code='user_email_exists')
        except User.DoesNotExist:
            return email

    def clean_username(self):
        username = self.cleaned_data.get('username')
        try:
            User.objects.get(username=username)
            raise ValidationError('User with this username already exists',
                                  code='user_username_exists')
        except User.DoesNotExist:
            return username

    def clean(self):
        super().clean()
        password_1 = self.cleaned_data['password']
        password_2 = self.cleaned_data['password_confirm']
        if password_1 != password_2:
            raise ValidationError('Passwords do not match',
                                  code='passwords_do_not_match')
        return self.cleaned_data


class UserChangeForm(forms.ModelForm):
    avatar = forms.ImageField(label='Аватар', required=False)
    birth_date = forms.DateField(label='День рождения', input_formats=['%Y-%m-%d', '%d.%m.%Y'], required=False)
    site = forms.URLField(max_length=255, label='Сайт', required=False)

    def get_initial_for_field(self, field, field_name):
        if field_name in self.Meta.profile_fields:
            return getattr(self.instance.profile, field_name)
        return super().get_initial_for_field(field, field_name)

    def clean_site(self):
        url = self.cleaned_data.get('site', '')
        if url:
            protocol, full_path = url.split('://', 1)
            site_name = full_path.split('/', 1)[0]
            site_name = site_name.split('?', 1)[0]
            print(site_name)
            if site_name != 'github.com':
                raise ValidationError('wrong site. only github.com))')
        return url

    def save(self, commit=True):
        user = super().save(commit=commit)
        user.profile = self.save_profile(commit)
        return user

    def save_profile(self, commit=True):
        profile, _ = Profile.objects.get_or_create(user=self.instance)
        for field in self.Meta.profile_fields:
            setattr(profile, field, self.cleaned_data.get(field))
        if not profile.avatar:
            profile.avatar = None
        if commit:
            profile.save()
        return profile

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'avatar', 'birth_date']
        profile_fields = ['avatar', 'birth_date', 'site']
        labels = {'first_name': 'Имя', 'last_name': 'Фамилия', 'email': 'Email'}


class PasswordChangeForm(forms.ModelForm):
    password = forms.CharField(label="New Password", strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Confirm the password", widget=forms.PasswordInput, strip=False)
    old_password = forms.CharField(label="old password", strip=False, widget=forms.PasswordInput)

    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Passwords do not match!')
        return password_confirm

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        if not self.instance.check_password(old_password):
            raise forms.ValidationError('Old password is incorrect!')
        return old_password

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['password', 'password_confirm', 'old_password']


# class SignUpForm(UserCreationForm):
#     email = forms.EmailField(required=True, label='Email')
#
#     class Meta(UserCreationForm.Meta):
#         fields = ('username', 'email')
#
#     def clean_email(self):
#         email = self.cleaned_data.get('email')
#         try:
#             User.objects.get(email=email)
#             raise ValidationError('Email already registered.', code='email_registered')
#         except User.DoesNotExist:
#             return email

source/accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import DetailView, UpdateView, ListView

from main.settings import HOST_NAME
from accounts.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth.models import User
from accounts.models import Token
from webapp.mixins import StatsMixin


class UsersView(StatsMixin, ListView):
    context_object_name = 'users'
    model = User
    template_name = 'user_list.html'


def login_view(request):
    context = {}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            next_url = request.GET.get('next')
            if next_url:
                return redirect(next_url)
            return redirect('webapp:index')
        else:
            context['has_error'] = True
    return render(request, 'login.html', context=context)


def logout_view(request):
    logout(request)
    return redirect('webapp:index')


def register_view(request):
    if request.method == 'GET':
        form = UserCreationForm()
        return render(request, 'register.html', {'form': form})
    elif request.method == 'POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            user = User(
                username=form.cleaned_data['username'],
                email=form.cleaned_data['email'],
                is_active=False
            )
            user.set_password(form.cleaned_data['password'])
            user.save()
            token = Token.objects.create(user=user)
            activation_url = HOST_NAME + reverse('accounts:user_activate') + '?token={}'.format(token)
            user.email_user('Register on localhost',
                            'To activate, follow the link: {}'.format(activation_url))

            return redirect("webapp:index")
        else:
            return render(request, 'register.html', {'form': form})


def user_activate(request):
    token_value = request.GET.get('token')
    try:
        token = Token.objects.get(token=token_value)
        user = token.user
        user.is_active = True
        user.save()
        token.delete()
        login(request, user)
        return redirect('webapp:index')
    except Token.DoesNotExist:
        return redirect('webapp:index')


class UserDetailView(StatsMixin, DetailView):
    model = User
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'


class UserPersonalInfoChangeView(UserPassesTestMixin, StatsMixin, UpdateView):
    model = User
    template_name = 'user_info_change.html'
    form_class = UserChangeForm
    context_object_name = 'user_obj'

    def test_func(self):
        return self.request.user.pk == self.kwargs['pk']

    def get_success_url(self):
        return reverse('accounts:detail', kwargs={'pk': self.object.pk})


class UserPasswordChangeView(UserPassesTestMixin, StatsMixin, UpdateView):
    model = User
    template_name = 'user_password_change.html'
    form_class = PasswordChangeForm
    context_object_name = 'user_obj'

    def test_func(self):
        return self.request.user.pk == self.kwargs['pk']

    def get_success_url(self):
        return reverse('accounts:login')

source/accounts/templates/login.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
         content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>account login</title>
</head>
<body>
<div class="container_login">
    <h1>account login</h1>
    <form action="{% url 'accounts:login' %}" method="post" class="text-center">
        {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}">
        {% if has_error %}
            <p class="form-error">The username or password you entered is incorrect.</p>
        {% endif %}
        <div class="form-group">
            <label for="username" class="form-label">Username:</label>
            <input type="text" name="username" id="username" class="form-control">
        </div>
        <div class="form-group">
            <label for="password" class="form-label">password:</label>
            <input type="password" name="password" id="password" class="form-control">
        </div>
        <button type="submit" class="action-btn">login to account</button>
    </form>
    <p class="text-center"><a href="{% url "webapp:index" %}" class="action-btn">to Home Page</a></p>
</div>
</body>
</html>

source/accounts/templates/register.html
{% extends 'base.html' %}

{% block content %}
    <h1>Sign Up</h1>
    <form action="{% url 'accounts:register' %}" method="post" class="text-center">
        {% include 'partial/tracker_form.html' with button_text='Сохранить' %}
    </form>
{% endblock %}

source/accounts/templates/user_detail.html
{% extends 'base.html' %}
{% block title %}User{% endblock %}
{% block menu %}
    {% if user.pk == user_obj.pk %}
        <li><a href="{% url "accounts:update" user_obj.pk %}" class="action-btn">Edit</a></li>
        <li><a href="{% url "accounts:password_change" user_obj.pk %}" class="action-btn">Change Password</a></li>
    {% endif %}
{% endblock %}
{% block content %}
    <h1>Personal Area</h1>
    <div class="row_image">
        <div class="image">
            {% if user_obj.profile.avatar %}
                <img class="avatar" src="{{ user_obj.profile.avatar.url }}" width="250" height="250" alt="user picture">
                {% else %}
                <img class="avatar" src="../../uploads/admin.png" alt="user picture">
            {% endif %}
        </div>
        <div class="row">
            <p>Username: {{ user_obj.username }}</p>
            <p>Name: {{ user_obj.first_name }}</p>
            <p>Last name: {{ user_obj.last_name }}</p>
            <p>Date of Birth: {{ user_obj.profile.birth_date|date:'d.m.Y' }}</p>
            <p>email: {{ user_obj.email }}</p>
            <p>git: {{ user_obj.profile.site }}</p>
            <p>about: {{ user_obj.profile.text }}</p>
        </div>
    </div>
{% endblock %}

source/accounts/templates/user_info_change.html
{% extends 'base.html' %}
{% block title %}Personal Area{% endblock %}
{% block menu %}
    <li><a href="{% url "accounts:detail" user_obj.pk %}" class="action-btn">Back</a></li>
    <li><a href="{% url "accounts:password_change" user_obj.pk %}" class="action-btn">Change Password</a></li>
{% endblock %}
{% block content %}
    <h1>Personal Area</h1>
    <form action="{% url "accounts:update" user_obj.pk %}" method="post" enctype="multipart/form-data">
        {% include 'partial/tracker_form.html' %}
    </form>
{% endblock %}

source/accounts/templates/user_list.html
{% extends 'base.html' %}
{% block menu %}
{% endblock %}

{% block content %}
        <div class="home_div">
            {% for user in users %}
                <div class="boss_div">
                    {% if user.profile.avatar %}
                        <img class="avatar" src="{{ user.profile.avatar.url }}" width="250" height="250" alt="user picture">
                    {% else %}
                        <img class="avatar" src="../../uploads/admin.png" alt="user picture">
                    {% endif %}
                    <h5>{{ user.email }}</h5>
                    <h5>{{ user.first_name }}</h5>
                    <div class="for_button">
                        <a href="{% url 'accounts:detail' user.pk %}" class="btn btn1">More >>></a>
                    </div>
                </div>
            {% endfor %}
        </div>
{% endblock %}

source/accounts/templates/user_password_change.html
{% extends 'base.html' %}
{% block title %}Change Password{% endblock %}
{% block menu_links %}
    <li><a href="{% url "accounts:detail" user_obj.pk %}" class="action-btn">Back</a></li>
    <li><a href="{% url "accounts:update" user_obj.pk %}" class="action-btn">Editing personal data</a></li>
{% endblock %}
{% block content %}
    <h1>Change Password</h1>
    <form action="{% url "accounts:password_change" user_obj.pk %}" method="post">
        {% include 'partial/tracker_form.html' %}
    </form>
{% endblock %}