source/accounts/urls.py
from django.urls import path
from accounts.views import login_view, logout_view, register_view, UsersView,\
    user_activate, UserDetailView, UserPersonalInfoChangeView, UserPasswordChangeView

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('register/activate/', user_activate, name='user_activate'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('<int:pk>/update', UserPersonalInfoChangeView.as_view(), name='update'),
    path('<int:pk>/password_change', UserPasswordChangeView.as_view(), name='password_change'),
    path('users/', UsersView.as_view(), name='all_users_view')
]

app_name = 'accounts'

source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/v2/', include('api_v2.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from webapp.views import *

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('tracker/<int:pk>/', TrackerView.as_view(), name='tracker'),
    path('tracker/add/', TrackerCreateView.as_view(), name='tracker_add'),
    path('tracker/<int:pk>/edit/', TrackerUpdate.as_view(), name='update_tracker'),
    path('tracker/<int:pk>/delete/', DeleteTracker.as_view(), name='delete_tracker'),
    path('tracker/type/', TypeView.as_view(), name='type_views'),
    path('tracker/type/add/', TypeAddView.as_view(), name='add_type'),
    path('tracker/type/delete/<int:pk>/', DeleteType.as_view(), name='delete_type'),
    path('tracker/type/update/<int:pk>/', UpdateTypeView.as_view(), name='update_type'),
    path('tracker/status/', StatusView.as_view(), name='status_views'),
    path('tracker/status/add/', StatusAddView.as_view(), name='add_status'),
    path('tracker/status/update/<int:pk>/', UpdateStatusView.as_view(), name='update_status'),
    path('tracker/status/delete/<int:pk>/', DeleteStatus.as_view(), name='delete_status'),
    path('projects/', ProjectView.as_view(), name='projects'),
    path('project/<int:pk>/', ProjectDetailView.as_view(), name='project_detail'),
    path('project/add/', ProjectCreateView.as_view(), name='project_create'),
    path('project/<int:pk>/edit/', ProjectUpdate.as_view(), name='project_update'),
    path('project/<int:pk>/delete/', ProjectDelete.as_view(), name='delete_project'),
    path('project/<int:pk>/add-tracker/', TrackerForProjectCreateView.as_view(), name='create_new_tracker')
]

app_name = 'webapp'

source/webapp/views/project_view.py
from abc import ABC
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls.base import reverse_lazy
from django.core.paginator import Paginator
from django.utils.http import urlencode
from django.views.generic import ListView, DetailView, DeleteView, UpdateView, CreateView
from webapp.forms import ProjectForm, SimpleSearchForm, TeamForm
from webapp.models import Project, Team
from django.urls import reverse
from django.core.exceptions import PermissionDenied
from webapp.mixins import StatsMixin


class ProjectView(StatsMixin, ListView):
    context_object_name = 'project'
    model = Project
    template_name = 'project/projects_view.html'
    ordering = ['created_at']

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(title__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset

    def get_search_form(self):
        return SimpleSearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None


class ProjectDetailView(StatsMixin, DetailView):
    model = Project
    template_name = 'project/project_detail_view.html'
    context_object_name = 'project'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['form'] = TrackerProjectForm()
        context['users_in_project'] = User.objects.filter(user_team__project=context['project'],
                                                          user_team__updated_at__isnull=True)
        trackers = context['project'].tracker_project.order_by('-created_at')
        self.paginate_comments_to_context(trackers, context)
        return context

    def paginate_comments_to_context(self, trackers, context):
        paginator = Paginator(trackers, 8)
        page_number = self.request.GET.get('page', 1)
        page = paginator.get_page(page_number)
        context['paginator'] = paginator
        context['page_obj'] = page
        context['trackers'] = page.object_list
        context['is_paginated'] = page.has_other_pages()


class ProjectCreateView(LoginRequiredMixin, StatsMixin, CreateView):
    template_name = 'project/project_create.html'
    model = Project
    form_class = ProjectForm
    success_url = reverse_lazy('projects')
    raise_exception = PermissionDenied

    def form_valid(self, form):
        users = form.cleaned_data.pop('users').values('pk')
        self.object = form.save()
        self.create_team(users)
        return HttpResponseRedirect(self.get_success_url())

    def create_team(self, users):
        users_team = list(users)
        users_team.append({'pk': self.request.user.pk})
        for user_obj in users_team:
            if user_obj:
                Team.objects.create(project=self.object, user_id=user_obj.get('pk'))


    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        users = User.objects.exclude(pk=self.request.user.pk)
        kwargs['users'] = users
        return kwargs

    def get_success_url(self):
        return reverse('webapp:project_detail', kwargs={'pk': self.object.pk})


class ProjectUpdate(UserPassesTestMixin, StatsMixin, LoginRequiredMixin, UpdateView, ABC):
    model = Project
    form_class = ProjectForm
    template_name = 'project/project_update.html'
    success_url = reverse_lazy('projects')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        users = User.objects.exclude(pk=self.request.user.pk)
        kwargs['users'] = users
        return kwargs

    def get_form(self, form_class=None):
        form = super().get_form(form_class=None)
        del form.fields['users']
        return form

    def test_func(self):
        project = Project.objects.get(pk=self.kwargs['pk'])
        team = project.project_user_team.filter(user=self.request.user)
        if len(team) != 0:
            return True
        return False

# [user1, user2, user3, user4] post data
# [user1, user2] initial
# create()

# [user2, user3] post data
# [user1, user2, user3, user4] initial
# delete()




class TeamUpdate(UserPassesTestMixin, StatsMixin, LoginRequiredMixin, UpdateView, ABC):
    model = Team
    form_class = TeamForm
    # template_name = 'project/project_update.html'
    success_url = reverse_lazy('projects')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        users = User.objects.exclude(pk=self.request.user.pk)
        kwargs['users'] = users
        return kwargs

    def test_func(self):
        team = Team.objects.get(pk=self.kwargs['pk'])
        team_in_team = team.objects.filter(user=self.request.user)
        if len(team_in_team) != 0:
            return True
        return False


class ProjectDelete(UserPassesTestMixin, StatsMixin, DeleteView):
    template_name = 'project/project_delete.html'
    model = Project
    context_object_name = 'project'
    success_url = reverse_lazy('projects')

    def test_func(self):
        project = Project.objects.get(pk=self.kwargs['pk'])
        team = project.project_user_team.filter(user=self.request.user)
        if len(team) != 0:
            return True
        return False

source/webapp/views/status_view.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import ProtectedError
from django.http import HttpResponse, HttpResponseRedirect
from django.urls.base import reverse, reverse_lazy
from django.views.generic import ListView, DeleteView, UpdateView, CreateView
from webapp.forms import StatusForm
from webapp.mixins import StatsMixin
from webapp.models import Status


class StatusView(StatsMixin, ListView):
    context_object_name = 'status'
    model = Status
    template_name = 'status/status.html'


class StatusAddView(LoginRequiredMixin, StatsMixin, CreateView):
    form_class = StatusForm
    template_name = 'status/add_status.html'
    model = Status

    def get_success_url(self):
        return reverse('status_views')


class DeleteStatus(LoginRequiredMixin, StatsMixin, DeleteView):
    template_name = 'status/status_delete.html'
    model = Status
    context_object_name = 'status'
    success_url = reverse_lazy('status_views')


class UpdateStatusView(LoginRequiredMixin, StatsMixin, UpdateView):
    model = Status
    form_class = StatusForm
    template_name = 'status/edit_status.html'
    redirect_url = 'status_views'

    def delete(self, request, *args, **kwargs):
        try:
            self.object = self.get_object()
            success_url = self.get_success_url()
            self.object.delete()
            return HttpResponseRedirect(success_url)
        except ProtectedError:
            return HttpResponse("<h2>This object is used, deletion is prohibited</h2>")

source/webapp/views/tracker_view.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.urls.base import reverse_lazy, reverse
from django.utils.http import urlencode
from django.views.generic import ListView, DetailView, DeleteView, UpdateView, CreateView
from webapp.forms import TrackerProjectForm, SimpleSearchForm
from webapp.models import Tracker, Project
from webapp.mixins import StatsMixin


class IndexView(StatsMixin, ListView):
    context_object_name = 'tracker'
    model = Tracker
    template_name = 'tracker/index.html'
    paginate_by = 3
    paginate_orphans = 1

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(summary__icontains=self.search_value) | Q(description__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset

    def get_search_form(self):
        return SimpleSearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None


class TrackerView(StatsMixin, DetailView):
    model = Tracker
    template_name = 'tracker/tracker.html'


class TrackerCreateView(UserPassesTestMixin, StatsMixin, CreateView):
    template_name = 'tracker/add_tracker.html'
    model = Tracker
    form_class = TrackerProjectForm

    def get_form(self, form_class=None):
        form = super().get_form(form_class=None)
        form.fields['project_id'].queryset = Project.objects.filter(project_user_team__user=self.request.user,
                                                                    project_user_team__updated_at__isnull=True)
        return form

    def get_form_kwargs(self):
        project = Project.objects.get(pk=self.kwargs['pk'])
        kwargs = super().get_form_kwargs()
        user = User.objects.filter(user_team__project=project)
        kwargs['user'] = user
        return kwargs

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.created_by = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('webapp:tracker', kwargs={'pk': self.object.pk})

    def test_func(self):
        if self.request.user.is_authenticated:
            return True
        return False


class TrackerForProjectCreateView(UserPassesTestMixin, StatsMixin, CreateView):
    form_class = TrackerProjectForm
    template_name = "tracker/add_tracker.html"

    def form_valid(self, form):
        project = Project.objects.get(pk=self.kwargs['pk'])
        self.object = form.save(commit=False)
        self.object.created_by = self.request.user
        self.object.project_id = project
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())

    def get_form_kwargs(self):
        project = Project.objects.get(pk=self.kwargs['pk'])
        kwargs = super().get_form_kwargs()
        user = User.objects.filter(user_team__project=project)
        kwargs['user'] = user
        return kwargs

    def test_func(self):
        project = Project.objects.get(pk=self.kwargs['pk'])
        team = project.project_user_team.filter(user=self.request.user)
        if len(team) != 0:
            return True
        return False

    def get_success_url(self):
        return reverse('webapp:tracker', kwargs={'pk': self.object.pk})


class TrackerUpdate(UserPassesTestMixin, StatsMixin, UpdateView):
    model = Tracker
    form_class = TrackerProjectForm
    template_name = 'tracker/edit.html'

    def test_func(self):
        issue = self.get_object()
        project = issue.project_id
        users_in_project = User.objects.filter(user_team__project=project, user_team__updated_at__isnull=True)
        return self.request.user in users_in_project

    def get_form_kwargs(self):
        project = Project.objects.get(tracker=self.object.pk)
        kwargs = super().get_form_kwargs()
        user = User.objects.filter(user_team__project=project)
        kwargs['user'] = user
        return kwargs

    def get_success_url(self):
        # if self.request.user in users_in_project:
        #     return True
        # return False
        return reverse('webapp:tracker', kwargs={'pk': self.object.pk})


class DeleteTracker(UserPassesTestMixin, StatsMixin, DeleteView):
    template_name = 'tracker/delete_tracker.html'
    model = Tracker
    context_object_name = 'tracker'
    success_url = reverse_lazy('webapp:index')

    def test_func(self):
        tracker = self.get_object()
        project = tracker.project_id
        users_in_project = User.objects.filter(user_team__project=project, user_team__updated_at__isnull=True)
        return self.request.user in users_in_project

source/webapp/views/type_view.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls.base import reverse, reverse_lazy
from django.db.models.deletion import ProtectedError
from django.http import HttpResponse
from django.views.generic import ListView, DeleteView, UpdateView, CreateView
from webapp.forms import TypeForm
from webapp.mixins import StatsMixin
from webapp.models import Type


class TypeView(StatsMixin, ListView):
    context_object_name = 'type'
    model = Type
    template_name = 'type/type.html'


class TypeAddView(LoginRequiredMixin, StatsMixin, CreateView):
    form_class = TypeForm
    template_name = 'type/add_type.html'
    model = Type

    def get_success_url(self):
        return reverse('type_views')


class UpdateTypeView(LoginRequiredMixin, StatsMixin, UpdateView):
    model = Type
    form_class = TypeForm
    template_name = 'type/edit _type.html'
    redirect_url = 'type_views'


class DeleteType(LoginRequiredMixin, StatsMixin, DeleteView):
    template_name = 'type/type_delete.html'
    model = Type
    context_object_name = 'type'
    success_url = reverse_lazy('type_views')

    def delete(self, request, *args, **kwargs):
        try:
            self.object = self.get_object()
            success_url = self.get_success_url()
            self.object.delete()
            return HttpResponseRedirect(success_url)
        except ProtectedError:
            return HttpResponse("<h2>This object is used, deletion is prohibited</h2>")

source/webapp/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Tracker{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    {% block styles %}{% endblock %}
</head>
<body>
<nav class="navbar">
   <div class="container">
       <ul class="menu">
           {% if request.user.is_authenticated %}
               <li class="menu-right">Hi, <a href="{% url 'accounts:detail' user.pk %}" class="action-user">{{ user.username }}</a>!</li>
                <li><a href="{% url 'accounts:logout'  %}" class="action-btn">Log Out</a></li>
                {% else %}
                    <li><a href="{% url 'accounts:login'  %}" class="action-btn">Log In</a></li>
                    <li><a href="{% url 'accounts:register' %}" class="action-btn">Sign Up</a></li>
                {% endif %}
           <li><a href="{% url 'accounts:all_users_view' %}" class="action-btn">Users</a></li>
           <li><a href="{% url 'webapp:index' %}" class="action-btn">Home</a></li>
         <li class="nav-item"><a href="#statsModal" class="action-btn" data-toggle="modal" data-target="#statsModal">
                Statistics
            </a></li>
           {% block menu %}{% endblock %}
       </ul>
   </div>
</nav>
<div class="container">
    <div class="for_margin">
    {% block content %}{% endblock %}
    </div>
</div>
 <div class="modal fade" id="statsModal" tabindex="-1" role="dialog" aria-labelledby="statsModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="statsModalLabel">Statistics</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <h4>You visited the pages:</h4>
                    <ul>
                        {% for page, count in visits.items %}
                            <li>{{ page }}: {{ count }} times</li>
                        {% endfor %}
                    </ul>
                    <p>Total {{ visits_total }} visits.</p>

                    <h4>You spent on the site:</h4>
                    <ul>
                        {% for page, count in times.items %}
                            <li>{{ page }}: {{ count|stringformat:".2f" }} seconds</li>
                        {% endfor %}
                    </ul>
                    <p>Total {{ times_total|stringformat:".2f" }} seconds</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">OK</button>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="application/javascript" src="{% static "js/main.js" %}"></script>
{% block scripts %}{% endblock %}
</body>
</html>

source/webapp/templates/tracker.html
{% extends 'base.html' %}
{% block title %}List{% endblock %}
{% block menu %}
    <li><a href="{% url 'update_tracker' pk=tracker.pk %}" class="action-btn">Edit</a></li>
    <li>
        <main>
            <div class="button js-button-campaign action-btn"><span>Delete</span></div>
        </main>
    </li>
    <div class="overlay js-overlay-campaign">
        <div class="popup js-popup-campaign">
            <form method="POST" action="{% url 'delete_tracker' pk=tracker.pk %}">
                {% csrf_token %}
                <h2>Are you sure you want to delete this?</h2>
                <button class="action-btn" type="submit">Yes</button>
                <p><a class="action-btn object-tools js-close-campaign">No</a></p>
            </form>
            <div class="close-popup js-close-campaign"></div>
        </div>
    </div>
{% endblock %}
{% block content %}
    <h3>summary: {{ tracker.summary }}</h3>
    <p class="for_text">Description: {{ tracker.description }}</p>
    <p>time of created: {{ tracker.created_at }}</p>
    <p>status: <b>{{ tracker.status }}</b>, type: <b>{{ tracker.type }}</b></p>
{% endblock %}